### ISSUE TITLE
win10可以用，但不能隐藏标题栏

### ISSUE THREAD

**Issue by jacklaplace** [dmscode/WinSize#1]
win10可以用，
可以调整窗口尺寸，
也可以把窗口置顶，
但不能隐藏窗口的标题栏。

是不是更新一下？

**Comment by dmscode** [comment]
因为有些程序并没有使用标准的系统窗口控件，就没有办法做到隐藏标题栏了。

**Comment by jacklaplace** [comment]
谢谢回复，明白了。
