### ISSUE TITLE
如何打开两个窗口并将两个窗口放置在固定位置

### ISSUE THREAD

**Issue by huzichai** [dmscode/WinSize#4]
希望通过AHK来完成，但是目前只能调整一个窗口的大小，没有办法打开两个窗口并分别设置两个窗口的位置。

**Comment by dmscode** [comment]
只能一个窗口一个窗口调节。

这里存在一些问题，哪两个窗口，这需要一些规则去确定，但如果不是用户确实指定的窗口肯定是会存在误判的。而且有两个窗口的需求就还有三个窗口的需求，还有所有窗口的需求……这是一个很复杂且难以找到合适方案的问题，所以虽然一直有人在提，然而并没有解决。

可以考虑自己使用程序调用 WinSize 来实现自己的需求，我感觉 Quicker 很适合作为这样的前置工具，不复杂，可以根据自己的需求定制，就不用像我这样考虑太多了。

**Comment by huzichai** [comment]
你好，经过您的提醒，实现了我的需求，把下面三个窗口排列。非常感谢。
run 'notepad.exe'
Sleep 500
Run 'D:\soft\0.pc软件\WinSize 5.10.3\WinSize-Cli.exe --layout="0|0|50sw|50sh" --sleep=10'

Sleep 1000
run 'mspaint.exe'
Sleep 500
Run 'D:\soft\0.pc软件\WinSize 5.10.3\WinSize-Cli.exe --layout="0|50sh|100sw|50sh" --sleep=10'

Sleep 1000
run 'D:\soft\vrji_soft\Navicat Premium 16\navicat2.exe'
Sleep 4000
Run 'D:\soft\0.pc软件\WinSize 5.10.3\WinSize-Cli.exe --layout="50sw|0|50sw|50sh" --sleep=10'

**Comment by dmscode** [comment]
有问题可以在小众软件论坛（ https://meta.appinn.net/ ）找到我，当然这里也可以的，只是可能反应慢一些，因为不太会用（捂脸）。这里我先 close 喵~
